import { createCurlParserWasm } from "./index.mjs";

const parser = await createCurlParserWasm();

const result = parser.parse({
  schemaVersion: "1.0",
  inputMode: "argv",
  argv: ["curl", "--http3", "--json", '{"a":1}', "https://example.com"],
  parseMode: "strict",
  runtimeProfile: {
    curlVersion: "8.20.0",
    protocols: [
      "dict",
      "file",
      "ftp",
      "ftps",
      "gopher",
      "gophers",
      "http",
      "https",
      "imap",
      "imaps",
      "ipfs",
      "ipns",
      "mqtt",
      "mqtts",
      "pop3",
      "pop3s",
      "rtsp",
      "scp",
      "sftp",
      "smtp",
      "smtps",
      "telnet",
      "tftp",
    ],
    features: [
      "alt-svc",
      "AsynchDNS",
      "brotli",
      "GSS-API",
      "HSTS",
      "HTTP2",
      "HTTP3",
      "HTTPS-proxy",
      "IDN",
      "IPv6",
      "Kerberos",
      "Largefile",
      "libz",
      "PSL",
      "SPNEGO",
      "SSL",
      "threadsafe",
      "TLS-SRP",
      "UnixSockets",
      "zstd",
    ],
    compile: {
      availableOptions: null,
      disabledOptions: [],
      defines: [],
    },
  },
  options: {
    loadDefaultCurlrc: false,
    allowHostFileRead: false,
    virtualFiles: {},
  },
});

console.log(JSON.stringify(result, null, 2));
